### ISSUE TITLE
MQ object issue

### ISSUE THREAD

**Issue by beginga** [pplu/aws-sdk-perl#322] opened 2019-03-26 10:44 UTC
Hello,

When I'm using the method ListBrokers (https://metacpan.org/pod/Paws::MQ::ListBrokers), I get this error message:

```
use Paws ;

my $region = 'eu-west-1' ;
 my $mq = Paws->service('MQ',region => $region);
 my $result = $mq->ListBrokers ;
```

```
Trace begun at /usr/local/share/perl5/Paws/Net/RestJsonResponse.pm line 32
Paws::Net::RestJsonResponse::unserialize_response('Paws::Net::RestJsonResponse=HASH(0x4150c90)', 'Paws::Net::APIResponse=HASH(0x41f95e8)') called at /usr/local/share/perl5/Paws/Net/RestJsonResponse.pm line 45
Paws::Net::RestJsonResponse::error_to_exception('Paws::Net::RestJsonResponse=HASH(0x4150c90)', 'Paws::MQ::ListBrokers=HASH(0x3c3e4e8)', 'Paws::Net::APIResponse=HASH(0x41f95e8)') called at /usr/local/share/perl5/Paws/Net/RestJsonResponse.pm line 20
Paws::Net::RestJsonResponse::process('Paws::Net::RestJsonResponse=HASH(0x4150c90)', 'Paws::MQ::ListBrokers=HASH(0x3c3e4e8)', 'Paws::Net::APIResponse=HASH(0x41f95e8)') called at /usr/local/share/perl5/Paws/Net/Caller.pm line 46
Paws::Net::Caller::caller_to_response('Paws::Net::Caller=HASH(0x259f760)', 'Paws::MQ=HASH(0x3019d78)', 'Paws::MQ::ListBrokers=HASH(0x3c3e4e8)', 'Paws::Net::APIResponse=HASH(0x41f95e8)') called at /usr/local/share/perl5/Paws/Net/RetryCallerRole.pm line 19
Paws::Net::RetryCallerRole::do_call('Paws::Net::Caller=HASH(0x259f760)', 'Paws::MQ=HASH(0x3019d78)', 'Paws::MQ::ListBrokers=HASH(0x3c3e4e8)') called at /usr/local/share/perl5/Paws/MQ.pm line 75
Paws::MQ::ListBrokers('Paws::MQ=HASH(0x3019d78)') called at Test.pl line 6
```

The call is working fine using the aws cli: aws mq list-brokers

Sam issue with ListConfigurations

Regards,

**Comment by pplu** [comment] 2019-04-01 08:34
Hi,

  I've been looking into this. It looks like the problem is here:
```diff 
diff --git a/lib/Paws/Net/RestJsonCaller.pm b/lib/Paws/Net/RestJsonCaller.pm
index 97fe69e39..b6d39b8f1 100644
--- a/lib/Paws/Net/RestJsonCaller.pm
+++ b/lib/Paws/Net/RestJsonCaller.pm
@@ -121,7 +121,7 @@ package Paws::Net::RestJsonCaller;
       #$request->headers->header( 'content-type'   => $self->content_type );
     } else {
       my $data = $self->_to_jsoncaller_params($call);
-      $request->content(encode_json($data));
+      $request->content(encode_json($data)) if (keys %$data > 0);
     }
     
     $request->method($call->_api_method);
```

The MQ API doesn't like the content of the HTTP request being '{}' if there is no parameters to be trasferred to the API. Can you please try out this patch?

**Comment by beginga** [comment] 2019-04-01 12:57
Jose,

Well done, that’s fixed the issue.

Regards,

**Comment by pplu** [comment] 2019-04-26 15:13
Paws 0.40 has just been uploaded to CPAN with a fix for this issue

**Closed by pplu** 2019-04-26 15:13 UTC
