### ISSUE TITLE
broken tests in feat/restjson_streamingresponses

### ISSUE THREAD

**Issue by karenetheridge** [pplu/aws-sdk-perl#163] opened 2017-04-14 23:39 UTC
just FYI - running tests in feat/restjson_streamingresponses at commit 825eeec56 I saw these failures:

```
: [ether@bourbon git/Paws]$; dzil test
[DZ] building distribution under .build/wbnUm9is3L for installation
[DZ] beginning to build Paws
[Prereqs::FromCPANfile] Parsing 'cpanfile' to extract prereqs
[DZ] writing Paws in .build/wbnUm9is3L
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Paws
Writing MYMETA.yml and MYMETA.json
cp bin/open_aws_console blib/script/open_aws_console
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/open_aws_console
cp bin/paws blib/script/paws
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/paws
cp bin/paws_make_testcase blib/script/paws_make_testcase
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/paws_make_testcase
cp bin/xml2yaml.sh blib/script/xml2yaml.sh
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/xml2yaml.sh
PERL_DL_NONLAZY=1 "/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01_load.t ............................. 9/? Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/CloudFront.pm line 2.
t/01_load.t ............................. 69/? Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/Route53.pm line 2.
t/01_load.t ............................. 72/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/S3.pm line 2.
t/01_load.t ............................. ok    
t/02_aws_object.t ....................... ok   
t/03_aws_default_object.t ............... ok   
t/04_credentials.t ...................... 11/? Error in JSON from metadata URL at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/Credential/InstanceProfile.pm line 72.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 60 just after 12.
t/04_credentials.t ...................... Dubious, test returned 60 (wstat 15360, 0x3c00)
All 12 subtests passed 
t/05_service_calls.t .................... "my" variable $cfn masks earlier declaration in same scope at t/05_service_calls.t line 428.
t/05_service_calls.t .................... 1/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/S3.pm line 2.
Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/CloudFront.pm line 2.
t/05_service_calls.t .................... 69/? Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/Route53.pm line 2.
Use of uninitialized value in subroutine entry at /Users/ether/.perlbrew/libs/25.11@std/lib/perl5/Net/Amazon/Signature/V4.pm line 102.
t/05_service_calls.t .................... ok    
t/10_responses.t ........................ 1/? Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/CloudFront.pm line 2.
t/10_responses.t ........................ 8064/? Use of uninitialized value in anonymous hash ({}) at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/Net/XMLResponse.pm line 98.
Use of uninitialized value in anonymous hash ({}) at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/Net/XMLResponse.pm line 98.
t/10_responses.t ........................ 8609/? Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/Route53.pm line 2.
t/10_responses.t ........................ 8784/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/S3.pm line 2.
t/10_responses.t ........................ ok      
t/11_client_exceptions.t ................ # Testing with caller Paws::Net::FurlCaller
t/11_client_exceptions.t ................ 5/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/S3.pm line 2.
Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/blib/lib/Paws/Route53.pm line 2.
# Testing with caller Paws::Net::Caller
t/11_client_exceptions.t ................ 62/? # Testing with caller Paws::Net::LWPCaller
t/11_client_exceptions.t ................ ok     
t/12_regions.t .......................... 1/? Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/t/../lib/Paws/CloudFront.pm line 2.
Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/t/../lib/Paws/Route53.pm line 2.
Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/wbnUm9is3L/t/../lib/Paws/S3.pm line 2.
t/12_regions.t .......................... 24/? No service for email at t/12_regions.t line 310.
t/12_regions.t .......................... ok     
t/13_client_connect_errors.t ............ # Default caller
t/13_client_connect_errors.t ............ 1/? # LWP caller
t/13_client_connect_errors.t ............ 3/? # Mojo caller
# 
# Furl caller
t/13_client_connect_errors.t ............ ok   
t/14_dns_client_errors.t ................ # Default caller
t/14_dns_client_errors.t ................ 1/? # LWP caller
t/14_dns_client_errors.t ................ 3/? # Mojo caller
# Furl caller
t/14_dns_client_errors.t ................ ok   
t/15_timeouts.t ......................... ok   
t/16_retries.t .......................... ok    
t/20_json_syntetic_responses.t .......... ok    
t/21_restjson_syntetic_responses.t ...... ok    
t/22_query_syntetic_responses.t ......... ok    
t/23_queryflatten_syntetic_responses.t .. ok    
t/99_pod_syntax.t ....................... ok         

Test Summary Report
-------------------
t/04_credentials.t                    (Wstat: 15360 Tests: 12 Failed: 0)
  Non-zero exit status: 60
  Parse errors: No plan found in TAP output
t/10_responses.t                      (Wstat: 0 Tests: 9889 Failed: 0)
  TODO passed:   6364, 9572
Files=17, Tests=17859, 245 wallclock secs ( 2.18 usr  0.26 sys + 102.67 cusr  2.54 csys = 107.65 CPU)
Result: FAIL
Failed 1/17 test programs. 0/17859 subtests failed.
make: *** [test_dynamic] Error 255
error running make test
```

**Comment by pplu** [comment] 2017-04-20 07:53
Hi,

   Thanks for the heads-up! It would seem that only 04_credentials is failing. It's not failing on travis, so I suppose it's something specific to your environment, and I would like to catch what it is. Is it possible you are you running or can reach some type of service on IP 169.254.169.254 in your environment? If you wget http://169.254.169.254/latest/meta-data/iam/security-credentials/ do you get anything?

**Comment by karenetheridge** [comment] 2017-04-20 18:26
That IP doesn't have anything responding to it.

Curiously, when I re-run the tests now, I get different results:

```
: [ether@bourbon git/Paws]$; dzil test --jobs 1
[DZ] building distribution under .build/oKVkumv6kC for installation
[DZ] beginning to build Paws
[Prereqs::FromCPANfile] Parsing 'cpanfile' to extract prereqs
[DZ] writing Paws in .build/oKVkumv6kC
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Paws
Writing MYMETA.yml and MYMETA.json
cp bin/open_aws_console blib/script/open_aws_console
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/open_aws_console
cp bin/paws blib/script/paws
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/paws
cp bin/paws_make_testcase blib/script/paws_make_testcase
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/paws_make_testcase
cp bin/xml2yaml.sh blib/script/xml2yaml.sh
"/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/xml2yaml.sh
PERL_DL_NONLAZY=1 "/Users/ether/perl5/perlbrew/perls/25.11/bin/perl5.25.11" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01_load.t ............................. 9/? Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/CloudFront.pm line 2.
t/01_load.t ............................. 69/? Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/Route53.pm line 2.
t/01_load.t ............................. 71/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/S3.pm line 2.
t/01_load.t ............................. ok    
t/02_aws_object.t ....................... ok   
t/03_aws_default_object.t ............... ok   
t/04_credentials.t ...................... ok    
t/05_service_calls.t .................... "my" variable $cfn masks earlier declaration in same scope at t/05_service_calls.t line 428.
t/05_service_calls.t .................... 1/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/S3.pm line 2.
Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/CloudFront.pm line 2.
Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/Route53.pm line 2.
Use of uninitialized value in subroutine entry at /Users/ether/.perlbrew/libs/25.11@std/lib/perl5/Net/Amazon/Signature/V4.pm line 102.
t/05_service_calls.t .................... ok    
t/10_responses.t ........................ 55/? Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/CloudFront.pm line 2.
t/10_responses.t ........................ 7878/? Use of uninitialized value in anonymous hash ({}) at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/Net/XMLResponse.pm line 98.
Use of uninitialized value in anonymous hash ({}) at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/Net/XMLResponse.pm line 98.
t/10_responses.t ........................ 8594/? Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Use of uninitialized value $got in string eq at (eval in cmp_ok) t/10_responses.t line 141.
Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/Route53.pm line 2.
t/10_responses.t ........................ 9507/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/S3.pm line 2.
t/10_responses.t ........................ ok      
t/11_client_exceptions.t ................ # Testing with caller Paws::Net::FurlCaller
t/11_client_exceptions.t ................ 5/? Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/S3.pm line 2.
Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/blib/lib/Paws/Route53.pm line 2.
# Testing with caller Paws::Net::Caller
t/11_client_exceptions.t ................ 62/? # Testing with caller Paws::Net::LWPCaller
t/11_client_exceptions.t ................ ok     
t/12_regions.t .......................... 2/? Paws::CloudFront is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/t/../lib/Paws/CloudFront.pm line 2.
Paws::Route53 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/t/../lib/Paws/Route53.pm line 2.
Paws::S3 is not stable / supported / entirely developed at /Volumes/sake/git/Paws/.build/oKVkumv6kC/t/../lib/Paws/S3.pm line 2.
No service for email at t/12_regions.t line 310.
t/12_regions.t .......................... ok     
t/13_client_connect_errors.t ............ # Default caller
t/13_client_connect_errors.t ............ 1/? # LWP caller
t/13_client_connect_errors.t ............ 3/? # Mojo caller
# 
t/13_client_connect_errors.t ............ 5/? # Furl caller
t/13_client_connect_errors.t ............ ok   
t/14_dns_client_errors.t ................ # Default caller
t/14_dns_client_errors.t ................ 1/? # LWP caller
t/14_dns_client_errors.t ................ 3/? # Mojo caller
# Furl caller
t/14_dns_client_errors.t ................ ok   
t/15_timeouts.t ......................... ok   
t/16_retries.t .......................... ok    
t/20_json_syntetic_responses.t .......... ok    
t/21_restjson_syntetic_responses.t ...... ok    
t/22_query_syntetic_responses.t ......... ok    
t/23_queryflatten_syntetic_responses.t .. ok    
t/99_pod_syntax.t ....................... ok         
All tests successful.

Test Summary Report
-------------------
t/10_responses.t                      (Wstat: 0 Tests: 9889 Failed: 0)
  TODO passed:   6364, 9572
Files=17, Tests=17883, 226 wallclock secs ( 1.62 usr  0.21 sys + 77.93 cusr  2.60 csys = 82.36 CPU)
Result: PASS
[DZ] all's well; removing .build/oKVkumv6kC

```

**Comment by pplu** [comment] 2017-05-18 22:46
Closing, as the branch was merged, and shipped to CPAN. I couldn't reproduce the error :(

**Closed by pplu** 2017-05-18 22:46 UTC
Labels: invalid
